# Generated by Django 4.2.6 on 2023-10-18 01:33

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Prefecture",
            fields=[
                ("code", models.CharField(max_length=2, primary_key=True, serialize=False, verbose_name="都道府県コード")),
                ("name", models.CharField(max_length=10, verbose_name="都道府県名")),
                ("geom", django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326, verbose_name="ジオメトリ")),
            ],
            options={
                "verbose_name": "都道府県",
                "verbose_name_plural": "都道府県",
                "db_table": "prefectures",
                "ordering": ["code"],
            },
        ),
    ]
