repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.1.0
    hooks:
      - id: ruff
        args: [
          --fix,
          --ignore=D100,
          --ignore=D101,
          --ignore=D104,
          --ignore=D105,
          --ignore=D106,
          --ignore=D203,
          --ignore=D212,
          --ignore=D400,
          --ignore=D415,
          --exit-non-zero-on-fix,
          --exclude=migrations,
          my_site
        ]
