version: "3.8"

services:
  app:
    # コンテナ名
    container_name: django-app
    # ビルドコンテキストをカレントディレクトリに設定
    # Dockerfileのパスを指定
    build:
      context: .
      dockerfile: containers/django/Dockerfile
    # ローカルのカレントディレクトリを、コンテナの/workspaceにマウント
    volumes:
      - .:/workspace
    # ローカルの8000ポートを、コンテナの8000ポートにマッピング
    ports:
      - 8000:8000
    # 環境変数ファイルを設定
    env_file:
      - .env
    # コンテナ起動時に実行するコマンドを設定
    entrypoint: /workspace/entrypoint.sh
    # コンテナ間の依存関係を設定
    depends_on:
      # dbコンテナを起動してからappコンテナを起動
      db:
        condition: service_healthy

  db:
    # コンテナ名
    container_name: postgres-db
    # コンテナイメージを指定
    image: xjr1300/postgres16-postgis34:latest
    # ポート番号を設定
    ports:
      - 5432:5432
    # ボリュームを永続化
    volumes:
      - postgres-db-data:/var/lib/postgresql/data
    # 環境変数ファイルを指定
    env_file:
      - .env
    # ヘルスチェック
    healthcheck:
      # コンテナ内で実行するコマンド
      test: psql -h localhost -U ${POSTGRES_USER} -d ${POSTGRES_DB} -c '\q'
      # ヘルスチェックの間隔
      interval: 10s
      # ヘルスチェックのタイムアウト
      timeout: 5s
      # ヘルスチェックのリトライ回数
      retries: 5

volumes:
  postgres-db-data:
