# Generated by Django 4.2.6 on 2023-10-18 07:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cities", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="city",
            name="pref_code",
            field=models.CharField(default="0", max_length=2, verbose_name="都道府県コード"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="city",
            name="pref_name",
            field=models.CharField(default="a", max_length=10, verbose_name="都道府県名"),
            preserve_default=False,
        ),
    ]
